import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";

/*
 * A real PostgreSQL instance, in process, for testing the migrations against.
 *
 * PGlite is Postgres compiled to WebAssembly, so this is not a simulation: the
 * migration files below are executed by the same planner, the same plpgsql, and
 * the same constraint machinery that Supabase runs. That is what makes it
 * possible to prove things a text search cannot — that the whole history applies
 * to an empty database, that the final schema really has no team objects left,
 * and that the transactional functions behave correctly under a version
 * conflict.
 */

const MIGRATION_DIR = fileURLToPath(new URL("../../supabase/migrations", import.meta.url));

export function migrationFiles() {
  return readdirSync(MIGRATION_DIR)
    .filter((name) => name.endsWith(".sql"))
    .sort();
}

export function readMigration(name: string) {
  return readFileSync(`${MIGRATION_DIR}/${name}`, "utf8");
}

/*
 * What a Supabase project provides before any of its own migrations run. Without
 * these the first historical migration cannot even parse: it references
 * `auth.users`, `auth.uid()`, the three API roles, and the Realtime publication.
 *
 * The default privileges matter. Supabase grants `all on tables` to `anon` and
 * `authenticated` for anything created in `public` afterwards, which is exactly
 * why the controller-auth migration has to revoke them explicitly. Setting them
 * here is what makes those revokes testable rather than decorative.
 */
const SUPABASE_BOOTSTRAP = `
  create role anon;
  create role authenticated;
  create role service_role;

  create schema if not exists auth;
  create table auth.users (id uuid primary key default gen_random_uuid());
  create function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;

  create publication supabase_realtime;

  alter default privileges in schema public
    grant all on tables to anon, authenticated, service_role;
`;

export type TestDatabase = PGlite;

/** An empty database with only the Supabase preamble applied. */
export async function createBareDatabase(): Promise<TestDatabase> {
  const db = await PGlite.create({ extensions: { pgcrypto } });
  await db.exec(SUPABASE_BOOTSTRAP);
  return db;
}

/** An empty database with the complete migration history applied, in order. */
export async function createMigratedDatabase(): Promise<TestDatabase> {
  const db = await createBareDatabase();
  for (const file of migrationFiles()) {
    try {
      await db.exec(readMigration(file));
    } catch (error) {
      throw new Error(
        `migration ${file} failed: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }
  return db;
}

/** `select` helper that returns plain rows. */
export async function rows<T = Record<string, unknown>>(
  db: TestDatabase,
  sql: string,
  params: unknown[] = [],
): Promise<T[]> {
  const result = await db.query<T>(sql, params);
  return result.rows;
}

export async function one<T = Record<string, unknown>>(
  db: TestDatabase,
  sql: string,
  params: unknown[] = [],
): Promise<T | undefined> {
  return (await rows<T>(db, sql, params))[0];
}

/** A UUID generated by the database, so tests never hand-write one. */
export async function newUuid(db: TestDatabase) {
  const row = await one<{ id: string }>(db, "select gen_random_uuid() as id");
  return row!.id;
}
