"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, Play, Search } from "lucide-react";
import { useState } from "react";
import { AppHeader } from "@/components/app-header";
import { Button } from "@/components/ui/button";
import { helpTopics, lessons } from "@/lib/guide";

export function LearningGuide() {
  const [query, setQuery] = useState("");
  const filtered = helpTopics.filter(topic => `${topic.label} ${topic.description}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <main id="main" className="min-h-svh bg-paper">
    <AppHeader />
    <div className="mx-auto w-[min(1120px,calc(100%-2.5rem))] py-12 sm:py-16">
      <div className="grid items-center gap-8 lg:grid-cols-[1.15fr_0.85fr]">
        <div><span className="text-[12px] font-bold tracking-widest text-violet-dark uppercase">The Timer field guide</span><h1 className="mt-4 text-[clamp(2.8rem,6vw,4.5rem)] leading-[1.02] font-semibold tracking-[-0.06em]">Your next event.<br />Under control.</h1><p className="mt-5 max-w-[540px] text-[16px] leading-relaxed text-text-muted">Find the right button, see what happens, and practise before the room goes live.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild variant="primary"><Link href="/guide/practice"><Play size={16} aria-hidden />Try a practice event</Link></Button><Button asChild><a href="#button-reference"><BookOpen size={16} aria-hidden />Find a button</a></Button></div></div>
        <div className="rounded-[24px] border border-violet/15 bg-violet-soft/60 p-7"><span className="text-[12px] font-semibold text-violet-dark">START HERE · ABOUT 4 MINUTES</span><h2 className="mt-4 text-[25px] font-semibold tracking-tight">Learn by doing.</h2><ol className="mt-5 grid gap-4">{["Start a speaker’s countdown", "Add fifteen seconds", "Pause, then change speakers"].map((text, i) => <li className="flex items-center gap-3 text-[14px]" key={text}><span className="grid size-8 shrink-0 place-items-center rounded-full bg-white font-semibold text-violet-dark">{i + 1}</span>{text}</li>)}</ol><p className="mt-6 text-[13px] leading-relaxed text-text-muted">Practice uses the actual event controls with sample data. No account or event password needed.</p></div>
      </div>
      <section className="mt-16" aria-labelledby="lessons-title"><div className="mb-6 flex flex-wrap items-baseline justify-between gap-3"><h2 id="lessons-title" className="text-[25px] font-semibold tracking-tight">What would you like to do?</h2><span className="text-[13px] text-text-muted">Short lessons. Start anywhere.</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{lessons.map(lesson => <Link key={lesson.id} href={`/guide/${lesson.id}`} className="group rounded-panel border border-line bg-white p-6 transition-colors hover:border-violet/40"><div className="flex justify-between gap-3 text-[12px] text-text-subtle"><span>{lesson.label}</span><span>{lesson.minutes}</span></div><h3 className="mt-5 text-[20px] font-semibold tracking-tight">{lesson.title}</h3><p className="mt-2 min-h-12 text-[14px] leading-relaxed text-text-muted">{lesson.description}</p><span className="mt-6 inline-flex items-center gap-2 text-[13px] font-semibold text-violet-dark">Open lesson<ArrowRight size={15} aria-hidden /></span></Link>)}</div></section>
      <section id="button-reference" className="mt-16 scroll-mt-24" aria-labelledby="reference-title"><h2 id="reference-title" className="text-[25px] font-semibold tracking-tight">Every button, explained.</h2><p className="mt-2 text-[14px] text-text-muted">On an event screen, open Help and choose Show me where to highlight a control.</p><label className="mt-6 flex max-w-[600px] items-center gap-3 rounded-control border border-line bg-white px-4"><Search size={17} aria-hidden className="text-text-subtle"/><span className="sr-only">Search buttons and actions</span><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Try “reset”, “invitation”, or “Zoom”…" className="min-h-12 min-w-0 flex-1 bg-transparent text-[16px] outline-offset-4" /></label><p className="my-3 text-[12px] text-text-subtle" role="status">{filtered.length} matching controls</p><div className="divide-y divide-line border-y border-line">{filtered.map(topic => <details key={topic.label} className="group py-1"><summary className="min-h-12 cursor-pointer py-3 text-[14px] font-semibold">{topic.label}<span className="ml-3 text-[12px] font-normal text-text-subtle">{topic.context === "control" ? "Event & display" : topic.context}</span></summary><p className="max-w-[800px] pb-3 text-[14px] leading-relaxed text-text-muted">{topic.description} <Link className="font-semibold text-violet-dark underline" href={`/guide/${topic.lesson}`}>Read lesson</Link></p></details>)}{!filtered.length && <p className="py-6 text-[14px] text-text-muted">No matching controls. Try another word or browse the lessons above.</p>}</div></section>
    </div>
  </main>;
}
